# Generated by Django 3.2.9 on 2021-12-06 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimages',
            name='post',
        ),
        migrations.RemoveField(
            model_name='textrow',
            name='post',
        ),
        migrations.AddField(
            model_name='postimages',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.textrow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textrow',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='textrow', to='main.post'),
            preserve_default=False,
        ),
    ]
