# Generated by Django 3.2.9 on 2021-11-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211117_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='PostImages',
        ),
    ]
