# Generated by Django 3.2.9 on 2021-11-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_images_postimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImages',
            new_name='PostImage',
        ),
    ]
