# Generated by Django 3.2.9 on 2021-11-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_postimages_postimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='PostImages',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='first_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
