# Generated by Django 3.2.9 on 2021-11-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_postimages_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='main/images/%Y/%m/%d/'),
        ),
    ]
