# Generated by Django 3.2.9 on 2021-11-19 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_postimages_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='paragraph_1',
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_3',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_4',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
