# Generated by Django 3.2.9 on 2021-11-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlepost',
            name='content',
        ),
        migrations.AddField(
            model_name='singlepost',
            name='paragraph_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlepost',
            name='paragraph_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlepost',
            name='paragraph_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlepost',
            name='paragraph_4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
